unlet! skip_defauts_vim
source $VIMRUNTIME/defaults.vim

set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest
set expandtab
set tabstop=4
set shiftwidth=4
set ignorecase
set smartcase
set wrapscan
set hlsearch
set breakindent
set nu
